version: 1.0
root: "./.tests/cloud_test/"
timeout: 3600 # 1 hour total timeout
providers:
  - name: "GKE"
    kind: "shell"
    instances: 1
    retry: 3
    enabled: false
    timeout: 300 # 5 minutes to start cluster
    parameters:
      GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

  - name: "Kind"
    kind: "shell"
    instances: 1
    retry: 3
    enabled: true
    timeout: 300 # 5 minutes to start cluster
    env:
      - CLUSTER_RULES_PREFIX=kind
    parameters:
      start: |
        make kind-start
        make kind-config
        make k8s-load-images -j 4
      stop: make kind-stop
      config: make kind-config-location

  - name: "Vagrant"
    kind: "shell"
    instances: 1
    retry: 3
    enabled: false
    timeout: 900 # 15 minutes to start cluster
    parameters:
      start: |
        make vagrant-start
        make k8s-config
        make k8s-load-images
      stop: make vagrant-destroy
      config: ./scripts/vagrant/.kube/config
reporting:
  junit-report: "junit.xml"
executions:
  - name: "Single cluster tests"
    tags:
      - basic
      - recover
      - usecase
    root: ./test/integration
    timeout: 15
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG