version: 1.0
root: "./.tests/cloud_test/"
timeout: 3600 # 1 hour total timeout
providers:
  - name: "GKE"
    kind: "shell"
    instances: 1
    retry: 3
    node-count: 2
    enabled: false
    timeout: 300 # 5 minutes to start cluster
    parameters:
      GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY

  - name: "Kind"
    kind: "shell"
    instances: 1
    node-count: 3
    retry: 10
    enabled: true
    timeout: 300 # 5 minutes to start cluster
    stop-delay: 10
    env:
      - CLUSTER_RULES_PREFIX=kind
    parameters:
      start: |
        make kind-config
        make kind-start
      stop: make kind-stop
      config: make kind-config-location
      start-config: |
        make k8s-load-images
        make k8s-config

  - name: "Vagrant"
    kind: "shell"
    instances: 1
    retry: 3
    node-count: 2
    enabled: true
    timeout: 900 # 15 minutes to start cluster
    env:
      - CLUSTER_RULES_PREFIX=vagrant
      - CONTAINER_BUILD_PREFIX=docker
      - CONTAINER_REPO=networkservicemesh
    parameters:
      start: |
        make vagrant-start
      start-config: |
        make k8s-load-images
        make k8s-config
      stop: make vagrant-suspend
      config: make vagrant-config-location
reporting:
  junit-report: "junit.xml"
executions:
  - name: "Single cluster tests"
    tags:
      - basic
      - recover
      - usecase
    root: ./test/integration
    timeout: 300
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG