version: 1.0
root: "./.tests/cloud_test/"
providers:
  - name: "GKE"
    kind: "shell"
    instances: 1
    average-start-time: 5
    average-shutdown-time: 5
    retry: 3
    enabled: false
    parameters:
      GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
  - name: "Kind"
    kind: "shell"
    instances: 1
    average-start-time: 5
    average-shutdown-time: 5
    retry: 3
    enabled: true
    env:
      - CLUSTER_RULES_PREFIX=kind
    parameters:
      start: |
        make kind-start
        make kind-config
        echo make k8s-load-images -j 4
      stop: echo make kind-stop
      config: make kind-config-location
  - name: "Vagrant"
    kind: "shell"
    instances: 1
    average-start-time: 5
    average-shutdown-time: 5
    retry: 3
    enabled: false
    parameters:
      start: |
        make vagrant-start
        make k8s-config
        make k8s-load-images
      stop: make vagrant-destroy
      config: ./scripts/vagrant/.kube/config
reporting:
  junit-report: "junit.xml"
executions:
  - name: "Single cluster tests"
    tags:
      - basic
      - recover
      - usecase
    root: ./test/integration
    timeout: 300
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG