version: 1.0
root: "./.tests/cloud_test/"
timeout: 3600 # 1 hour total timeout
providers:
  - name: "packet"
    kind: "shell"
    instances: 1
    retry: 0
    node-count: 2
    enabled: true
    timeout: 1800 # 30 minutes to start cluster
    env:
      - CLUSTER_RULES_PREFIX=packet
      - CLUSTERw_NAME=$(cluster-name)-$(uuid)
      - KUBECONFIG=$(tempdir)/config
      - TERRAFORM_ROOT=$(tempdir)/terraform
      - TF_VAR_auth_token=${PACKET_AUTH_TOKEN}
      - TF_VAR_master_hostname=devci-${CLUSTER_NAME}-master
      - TF_VAR_worker1_hostname=devci-${CLUSTER_NAME}-worker1
      - TF_VAR_project_id=${PACKET_PROJECT_ID}
      - TF_VAR_public_key=${TERRAFORM_ROOT}/sshkey.pub
      - TF_VAR_public_key_name=key-${CLUSTER_NAME}
      - TF_LOG=DEBUG
    env-check:
      - PACKET_AUTH_TOKEN
      - PACKET_PROJECT_ID
      - COMMIT
    parameters:
      install: |
        mkdir -p ${TERRAFORM_ROOT}
        ssh-keygen -t rsa -f ${TERRAFORM_ROOT}/sshkey -q -N ""
        ssh-add ${TERRAFORM_ROOT}/sshkey
        cp -a scripts/terraform/ ${TERRAFORM_ROOT}/
      start: |
        make packet-init
        make packet-start
      stop: make packet-stop
      #config: # We do not need it since we put KUBECONFIG into env.
      start-config: |
        make k8s-config
  - name: "gke"
    kind: "shell"
    instances: 2
    retry: 5
    node-count: 2
    enabled: false
    timeout: 1800 # 30 minutes to start cluster
    env:
      - GOOGLE_PROJECT_ID=ci-management
      - CLUSTER_RULES_PREFIX=gke
      - GKE_CLUSTER_NAME=$(cluster-name)-$(uuid)
      - CONTAINER_REPO=networkservicemesh
      - KUBECONFIG=$(tempdir)/config
      - GKE_CLUSTER_ZONE=$(zone-selector)
      - GKE_CLUSTER_TYPE=n1-standard-2
      - GKE_CLUSTER_NUM_NODES=2
    env-check:
      - GCLOUD_SERVICE_KEY
      - COMMIT
    parameters:
      install: ./.cloudtest/gke/init.sh
      zone-selector: ./.cloudtest/gke/list_zones.sh  # List zones
      start: |
        make gke-start
        make k8s-config
      stop: make gke-destroy
      #config: # We do not need it since we put KUBECONFIG into env.
      start-config: |
        make k8s-config
  - name: "Kind"
    kind: "shell"
    instances: 1
    node-count: 3
    retry: 10
    enabled: false
    timeout: 300 # 5 minutes to start cluster
    stop-delay: 10
    env:
      - CLUSTER_RULES_PREFIX=kind
    parameters:
      start: |
        make kind-config
        make kind-start
      stop: make kind-stop
      config: make kind-config-location
      start-config: |
        make k8s-load-images
        make k8s-config

  - name: "Vagrant"
    kind: "shell"
    instances: 1
    retry: 3
    node-count: 2
    enabled: false
    timeout: 900 # 15 minutes to start cluster
    env:
      - CLUSTER_RULES_PREFIX=vagrant
      - CONTAINER_BUILD_PREFIX=docker
      - CONTAINER_REPO=networkservicemesh
    parameters:
      start: |
        make vagrant-start
      config: make vagrant-config-location
      prepare: |
        make k8s-load-images
        make k8s-config
      stop: make vagrant-suspend
reporting:
  junit-report: "junit.xml"
executions:
  - name: "Single cluster tests"
    tags:
      - basic
      - recover
      - usecase
    root: ./test/integration
    timeout: 300
    cluster-count: 1
    kubernetes-env:
      - KUBECONFIG