---
apiVersion: extensions/v1beta1
kind: DaemonSet
spec:
  template:
    spec:
      containers:
        - name: alpine-img
          image: alpine:latest
          command: ['tail', '-f', '/dev/null']
          volumeMounts:
            - name: sources
              mountPath: /go/src
      initContainers:
        - name: nsc
          image: networkservicemesh/nsc:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NSC_LABELS
              value: "app=icmp"
            - name: NETWORK_SERVICES
              value: "nsm1:icmp-responder"
          resources:
            limits:
              nsm.ligato.io/socket: 1
      volumes:
        - hostPath:
            path: /go/src
            type: DirectoryOrCreate
          name: sources
metadata:
  name: nsmd-client
  namespace: default
